module.exports = {
  QUANTIFIER : 'QUANTIFIER',
  BOUNDARY : 'BOUNDARY',
  GROUPID : 'GROUPID',
  GROUP : 'GROUP',
  ASSERTIONS : 'ASSERTIONS',
  CHARSET : 'CHARSET',
  PRESETSET : 'PRESETSET',
  RANGECHARSET : 'RANGECHARSET',
  LOGICOR : 'LOGICOR',
  CHARS : 'CHARS',
};